### ISSUE TITLE
Error Microsoft .NET when load Phasmofobia Folder

### ISSUE THREAD

**Issue by Neinndall** [RazTools/Studio#11]
When I load the phasmophobia folder, it seems that it doesn't load the assets, there will be some problem with some file that is not compatible or I don't know.

Here is the error.

```
************* Exception **************
System.IO.IOException: Stream was too long.
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Compression.DeflateStream.CopyToStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Strategies.BufferedFileStreamStrategy.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.FileStream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Compression.DeflateStream.CopyToStream.CopyFromSourceToDestination()
   at System.IO.Compression.DeflateStream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Compression.GZipStream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at AssetStudio.ImportHelper.DecompressGZip(FileReader reader) in D:\a\Studio\Studio\AssetStudio\ImportHelper.cs:line 69
   at AssetStudio.AssetsManager.LoadFile(FileReader reader) in D:\a\Studio\Studio\AssetStudio\AssetsManager.cs:line 126
   at AssetStudio.AssetsManager.Load(String[] files) in D:\a\Studio\Studio\AssetStudio\AssetsManager.cs:line 83
   at AssetStudio.AssetsManager.LoadFolder(String path) in D:\a\Studio\Studio\AssetStudio\AssetsManager.cs:line 62
   at AssetStudioGUI.AssetStudioGUIForm.<>c__DisplayClass57_0.<loadFolder_Click>b__0() in D:\a\Studio\Studio\AssetStudioGUI\AssetStudioGUIForm.cs:line 223
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at AssetStudioGUI.AssetStudioGUIForm.loadFolder_Click(Object sender, EventArgs e) in D:\a\Studio\Studio\AssetStudioGUI\AssetStudioGUIForm.cs:line 223
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

************** Ensamblados cargados **************
System.Private.CoreLib
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Private.CoreLib.dll
----------------------------------------
AssetStudioGUI
    Versión del ensamblado: 0.90.0.0
    Versión Win32: 0.90.00
    Código base: file:///D:/Descargas/Programas%20PBE,%20LoR%20y%20DBD/PHA/AssetStudio_v0.90.00/AssetStudioGUI.dll
----------------------------------------
System.Runtime
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Versión del ensamblado: 6.0.2.0
    Versión Win32: 6.0.1022.47606
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/System.Windows.Forms.dll
----------------------------------------
System.Windows.Forms.Primitives
    Versión del ensamblado: 6.0.2.0
    Versión Win32: 6.0.1022.47606
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/System.Windows.Forms.Primitives.dll
----------------------------------------
System.ComponentModel.Primitives
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.ComponentModel.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Collections.Specialized.dll
----------------------------------------
AssetStudioUtility
    Versión del ensamblado: 0.90.0.0
    Versión Win32: 0.90.00
    Código base: file:///D:/Descargas/Programas%20PBE,%20LoR%20y%20DBD/PHA/AssetStudio_v0.90.00/AssetStudioUtility.dll
----------------------------------------
OpenTK.Graphics
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.0.0.0
    Código base: file:///D:/Descargas/Programas%20PBE,%20LoR%20y%20DBD/PHA/AssetStudio_v0.90.00/OpenTK.Graphics.dll
----------------------------------------
OpenTK.Mathematics
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.0.0.0
    Código base: file:///D:/Descargas/Programas%20PBE,%20LoR%20y%20DBD/PHA/AssetStudio_v0.90.00/OpenTK.Mathematics.dll
----------------------------------------
System.Drawing.Common
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/System.Drawing.Common.dll
----------------------------------------
System.Threading
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Collections.dll
----------------------------------------
System.Threading.Thread
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Threading.Thread.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.ComponentModel.TypeConverter.dll
----------------------------------------
Microsoft.Win32.Primitives
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
Accessibility
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 6.0.1022.47606
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/Accessibility.dll
----------------------------------------
OpenTK.WinForms
    Versión del ensamblado: 1.0.0.0
    Versión Win32: 1.0.0.0
    Código base: file:///D:/Descargas/Programas%20PBE,%20LoR%20y%20DBD/PHA/AssetStudio_v0.90.00/OpenTK.WinForms.dll
----------------------------------------
OpenTK.Windowing.Common
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.0.0.0
    Código base: file:///D:/Descargas/Programas%20PBE,%20LoR%20y%20DBD/PHA/AssetStudio_v0.90.00/OpenTK.Windowing.Common.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.Concurrent
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Collections.Concurrent.dll
----------------------------------------
System.ComponentModel
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.ComponentModel.dll
----------------------------------------
System.Numerics.Vectors
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Numerics.Vectors.dll
----------------------------------------
System.Memory
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Memory.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Resources.Extensions
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Versión del ensamblado: 6.0.2.0
    Versión Win32: 6.0.1022.47606
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/System.Drawing.dll
----------------------------------------
OpenTK.Windowing.Desktop
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.0.0.0
    Código base: file:///D:/Descargas/Programas%20PBE,%20LoR%20y%20DBD/PHA/AssetStudio_v0.90.00/OpenTK.Windowing.Desktop.dll
----------------------------------------
System.Diagnostics.Process
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Diagnostics.Process.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.ObjectModel
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.ObjectModel.dll
----------------------------------------
AssetStudio
    Versión del ensamblado: 0.90.0.0
    Versión Win32: 0.90.00
    Código base: file:///D:/Descargas/Programas%20PBE,%20LoR%20y%20DBD/PHA/AssetStudio_v0.90.00/AssetStudio.dll
----------------------------------------
System.Private.Uri
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Private.Uri.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Linq
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Linq.dll
----------------------------------------
System.Xml.ReaderWriter
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Private.Xml.dll
----------------------------------------
System.Text.RegularExpressions
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Text.RegularExpressions.dll
----------------------------------------
System.Net.WebClient
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Net.WebClient.dll
----------------------------------------
System.Text.Encoding.Extensions
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Text.Encoding.Extensions.dll
----------------------------------------
System
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Xml.XmlSerializer
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Xml.XmlSerializer.dll
----------------------------------------
Mono.Cecil
    Versión del ensamblado: 0.11.4.0
    Versión Win32: 0.11.4.0
    Código base: file:///D:/Descargas/Programas%20PBE,%20LoR%20y%20DBD/PHA/AssetStudio_v0.90.00/Mono.Cecil.dll
----------------------------------------
netstandard
    Versión del ensamblado: 2.1.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/netstandard.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Reflection.Primitives.dll
----------------------------------------
System.Console
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Console.dll
----------------------------------------
Newtonsoft.Json
    Versión del ensamblado: 13.0.0.0
    Versión Win32: 13.0.3.27908
    Código base: file:///D:/Descargas/Programas%20PBE,%20LoR%20y%20DBD/PHA/AssetStudio_v0.90.00/Newtonsoft.Json.dll
----------------------------------------
System.Linq.Expressions
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Linq.Expressions.dll
----------------------------------------
System.Runtime.Numerics
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Runtime.Numerics.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Data.Common
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Data.Common.dll
----------------------------------------
AssetStudio.PInvoke
    Versión del ensamblado: 0.90.0.0
    Versión Win32: 0.90.00
    Código base: file:///D:/Descargas/Programas%20PBE,%20LoR%20y%20DBD/PHA/AssetStudio_v0.90.00/AssetStudio.PInvoke.dll
----------------------------------------
System.Collections.NonGeneric
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Collections.NonGeneric.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Threading.ThreadPool
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Threading.ThreadPool.dll
----------------------------------------
System.IO.Compression
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.IO.Compression.dll
----------------------------------------
System.Runtime.Loader
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    Versión del ensamblado: 6.0.2.0
    Versión Win32: 6.0.1022.47606
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.10/es/System.Windows.Forms.resources.dll
----------------------------------------
System.Diagnostics.StackTrace
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Versión del ensamblado: 6.0.0.0
    Versión Win32: 6.0.1022.47605
    Código base: file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Collections.Immutable.dll
----------------------------------------

************** Depuración JIT **************



```

**Comment by Razmoth** [comment]
Greetings,

Seems like one of the archives in that game folder is too large to decompress in memory, try decompressing it with an external tool first then load that output.

**Comment by Neinndall** [comment]
will be fixed soon?

**Comment by Neinndall** [comment]
Ill add the console error when i add individual files.


```
[Info] Target Game type is Normal
[Info] [UnityCN] Selected Key is PGR GLB/KR (6B75726F6B75726F6B75726F6B75726F)
[Info] Loading C:\Program Files (x86)\Steam\steamapps\common\Phasmophobia\Phasmophobia_Data\sharedassets9.assets
[Info] Loading C:\Program Files (x86)\Steam\steamapps\common\Phasmophobia\Phasmophobia_Data\sharedassets6.assets
[Info] Loading C:\Program Files (x86)\Steam\steamapps\common\Phasmophobia\Phasmophobia_Data\sharedassets7.assets
[Info] Loading C:\Program Files (x86)\Steam\steamapps\common\Phasmophobia\Phasmophobia_Data\sharedassets8.assets
[Info] Loading C:\Program Files (x86)\Steam\steamapps\common\Phasmophobia\Phasmophobia_Data\sharedassets3.assets
[Info] Loading C:\Program Files (x86)\Steam\steamapps\common\Phasmophobia\Phasmophobia_Data\sharedassets4.assets
[Info] Loading C:\Program Files (x86)\Steam\steamapps\common\Phasmophobia\Phasmophobia_Data\sharedassets5.assets
[Info] Loading C:\Program Files (x86)\Steam\steamapps\common\Phasmophobia\Phasmophobia_Data\sharedassets2.assets
[Info] Loading C:\Program Files (x86)\Steam\steamapps\common\Phasmophobia\Phasmophobia_Data\sharedassets13.assets
[Info] Loading C:\Program Files (x86)\Steam\steamapps\common\Phasmophobia\Phasmophobia_Data\sharedassets10.assets
[Info] Loading C:\Program Files (x86)\Steam\steamapps\common\Phasmophobia\Phasmophobia_Data\sharedassets11.assets
[Info] Loading C:\Program Files (x86)\Steam\steamapps\common\Phasmophobia\Phasmophobia_Data\sharedassets12.assets
[Info] Loading C:\Program Files (x86)\Steam\steamapps\common\Phasmophobia\Phasmophobia_Data\resources.assets
[Info] Loading C:\Program Files (x86)\Steam\steamapps\common\Phasmophobia\Phasmophobia_Data\sharedassets1.assets
[Info] Loading C:\Program Files (x86)\Steam\steamapps\common\Phasmophobia\Phasmophobia_Data\globalgamemanagers.assets
[Info] Loading C:\Program Files (x86)\Steam\steamapps\common\Phasmophobia\Phasmophobia_Data\sharedassets0.assets
[Info] Loading C:\Program Files (x86)\Steam\steamapps\common\Phasmophobia\Phasmophobia_Data\Resources\unity_builtin_extra
[Info] Loading C:\Program Files (x86)\Steam\steamapps\common\Phasmophobia\Phasmophobia_Data\Resources\unity default resources
[Info] Read assets...
[Error] Unable to load object
Assets sharedassets9.assets
Path
Type Shader
PathID 1009
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at AssetStudio.EndianBinaryReader.ReadInt32() in D:\a\Studio\Studio\AssetStudio\EndianBinaryReader.cs:line 47
   at AssetStudio.SerializedProgramParameters..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 504
   at AssetStudio.SerializedProgram..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 728
   at AssetStudio.SerializedPass..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 803
   at AssetStudio.SerializedSubShader..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 857
   at AssetStudio.SerializedShader..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 912
   at AssetStudio.Shader..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 998
   at AssetStudio.AssetsManager.ReadAssets() in D:\a\Studio\Studio\AssetStudio\AssetsManager.cs:line 706
[Error] Unable to load object
Assets sharedassets9.assets
Path
Type Shader
PathID 1010
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at AssetStudio.EndianBinaryReader.ReadInt32() in D:\a\Studio\Studio\AssetStudio\EndianBinaryReader.cs:line 47
   at AssetStudio.VectorParameter..ctor(EndianBinaryReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 327
   at AssetStudio.ConstantBuffer..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 417
   at AssetStudio.SerializedProgramParameters..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 538
   at AssetStudio.SerializedProgram..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 728
   at AssetStudio.SerializedPass..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 803
   at AssetStudio.SerializedSubShader..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 857
   at AssetStudio.SerializedShader..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 912
   at AssetStudio.Shader..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 998
   at AssetStudio.AssetsManager.ReadAssets() in D:\a\Studio\Studio\AssetStudio\AssetsManager.cs:line 706
[Error] Unable to load object
Assets sharedassets9.assets
Path
Type Shader
PathID 1011
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadSByte()
   at AssetStudio.VectorParameter..ctor(EndianBinaryReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 327
   at AssetStudio.ConstantBuffer..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 417
   at AssetStudio.SerializedProgramParameters..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 538
   at AssetStudio.SerializedProgram..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 728
   at AssetStudio.SerializedPass..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 803
   at AssetStudio.SerializedSubShader..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 857
   at AssetStudio.SerializedShader..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 912
   at AssetStudio.Shader..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 998
   at AssetStudio.AssetsManager.ReadAssets() in D:\a\Studio\Studio\AssetStudio\AssetsManager.cs:line 706
[Error] Unable to load object
Assets sharedassets6.assets
Path
Type Shader
PathID 745
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at AssetStudio.EndianBinaryReader.ReadInt32() in D:\a\Studio\Studio\AssetStudio\EndianBinaryReader.cs:line 47
   at AssetStudio.SerializedProgramParameters..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 531
   at AssetStudio.SerializedProgram..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 728
   at AssetStudio.SerializedPass..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 803
   at AssetStudio.SerializedSubShader..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 857
   at AssetStudio.SerializedShader..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 912
   at AssetStudio.Shader..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 998
   at AssetStudio.AssetsManager.ReadAssets() in D:\a\Studio\Studio\AssetStudio\AssetsManager.cs:line 706
```

**Comment by Razmoth** [comment]
Greetings,

This probably means that the game has custom shader type tree definition, you can disable it from `Export Options -> Disable Shader` and try again

**Comment by Neinndall** [comment]
Hello! 

I had to disable the "disable shaders" option and select only the assets files instead of the entire folder, I don't know if this will be hotfixed in a future version, since it is more comfortable for the user to select folder and let the program know what do.

I also add that it has taken about... 3 minutes for all the assets to be loaded individually in the program.

**Comment by Neinndall** [comment]
hi!

Today with the new version:

![image](https://github.com/RazTools/Studio/assets/66384195/2faf777b-5a12-4767-855a-e1dfa579675c)


`Unclogged exception in the application. If you click continue, the app will ignore this error and try to continue. If you click exit, the app will close. Stream was too long`

**Comment by Razmoth** [comment]
Greetings,

As long as `Shader` is disabled, it shouldn't affect loading at all.

**Comment by Neinndall** [comment]
Hello, I'm reopening this thread because it's on topic! I was testing the new version and I tell you

`File/Load Folder` and `Phasmophobia`
![image](https://github.com/RazTools/Studio/assets/66384195/56898655-5346-46ae-a6d2-c81a1fcfe422)

After that...
![image](https://github.com/RazTools/Studio/assets/66384195/668b58cb-01de-4b75-b5ee-0029ca1ec122)

So, Studio forces me to upload individual files...
