### ISSUE TITLE
Lz4 Error

### ISSUE THREAD

**Issue by sunkhaskasis** [RazTools/Studio#12]
The files from this game have `UnityFS` header, but Studio can't open them, resulting in this error:
`System.IO.IOException: Lz4 decompression error, write -1 bytes but expected 130156 bytes
   at AssetStudio.BundleFile.ReadBlocks(FileReader reader, Stream blocksStream) in D:\a\Studio\Studio\AssetStudio\BundleFile.cs:line 493
   at AssetStudio.BundleFile..ctor(FileReader reader, Game game) in D:\a\Studio\Studio\AssetStudio\BundleFile.cs:line 113
   at AssetStudio.AssetsManager.LoadBundleFile(FileReader reader, String originalPath, Int64 originalOffset, Boolean log) in D:\a\Studio\Studio\AssetStudio\AssetsManager.cs:line 265`
Possible encryption? The game is called "创造与魔法" in Chinese; apparently localized as "Utopia: Origin" in the west.
[assets.zip](https://github.com/RazTools/Studio/files/12396773/assets.zip)

**Comment by Razmoth** [comment]
Greetings,

This file is indeed encrypted, make sure to select `NetEase` game from `Options -> Specify Game` before loading it.
