### ISSUE TITLE
About the UnityCNLive2DExtractor export problem

### ISSUE THREAD

**Issue by PackageInstaller** [RazTools/Studio#18]
I know I shouldn't submit feedback here. Please forgive me for this behavior because I can't find a place to submit issues in your [project](https://github.com/Razmoth/UnityCNLive2DExtractor), so I will give feedback here.

When I tried to export the Live2D assets of the Neural Cloud game (total 300+Mib size), it threw these exceptions and the program stopped after exporting the assets of three characters. I don't know what's going on and hope get your help

This is one of the files [haze_vow.zip](https://github.com/RazTools/Studio/files/12700751/haze_vow.zip) that will cause errors, I hope it will be helpful to you.

```
D:\Unpack Tools\UnityCNLive2DExtractor>"D:\Unpack Tools\UnityCNLive2DExtractor\UnityLive2DExtractor.exe" C:\Users\Neko\Desktop\l2d 4
[UnityCN] Selected Key is Neural Cloud (31636162383436663532393031633965)
Loading...
Extract assets/res/character/abigail_p2/l2d
Extract assets/res/character/aki_carnival/l2d
Extract assets/res/character/aki_p2/l2d
Unhandled exception. System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at AssetStudio.EndianBinaryReader.ReadInt32() in D:\a\CNStudio\CNStudio\AssetStudio\EndianBinaryReader.cs:line 42
   at AssetStudio.BinaryReaderExtensions.ReadAlignedString(BinaryReader reader) in D:\a\CNStudio\CNStudio\AssetStudio\Extensions\BinaryReaderExtensions.cs:line 35
   at UnityLive2DExtractor.CubismPhysicsOutput..ctor(EndianBinaryReader reader) in D:\a\UnityCNLive2DExtractor\UnityCNLive2DExtractor\UnityCNLive2DExtractor\CubismPhysicsRig.cs:line 64
   at UnityLive2DExtractor.CubismPhysicsSubRig..ctor(EndianBinaryReader reader) in D:\a\UnityCNLive2DExtractor\UnityCNLive2DExtractor\UnityCNLive2DExtractor\CubismPhysicsRig.cs:line 123
   at UnityLive2DExtractor.CubismPhysicsRig..ctor(EndianBinaryReader reader) in D:\a\UnityCNLive2DExtractor\UnityCNLive2DExtractor\UnityCNLive2DExtractor\CubismPhysicsRig.cs:line 145
   at UnityLive2DExtractor.Program.ParsePhysics(MonoBehaviour physics) in D:\a\UnityCNLive2DExtractor\UnityCNLive2DExtractor\UnityCNLive2DExtractor\Program.cs:line 362
   at UnityLive2DExtractor.Program.Main(String[] args) in D:\a\UnityCNLive2DExtractor\UnityCNLive2DExtractor\UnityCNLive2DExtractor\Program.cs:line 147

D:\Unpack Tools\UnityCNLive2DExtractor>
```

**Comment by Razmoth** [comment]
Greetings,

Thanks for reporting the issue, will unlock issues on that repository.

As for the sample itself, seems like it's a modified version of `Live2D` physics.
