### ISSUE TITLE
请问一下，这个问题什么时候能解决

### ISSUE THREAD

**Issue by saveend** [RazTools/Studio#32]
[Info] Target Game type is Normal
[Warning] CABMap is not build, skip resolving dependencies...
[Info] Loading C:\Users\Administrator\Desktop\Data\data.unity3d
[Info] Read assets...
[Error] Unable to load object
Assets unity_builtin_extra
Path C:\Users\Administrator\Desktop\Data\data.unity3d
Type Shader
PathID 6
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at AssetStudio.EndianBinaryReader.ReadInt32() in D:\a\Studio\Studio\AssetStudio\EndianBinaryReader.cs:line 47
   at AssetStudio.VectorParameter..ctor(EndianBinaryReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 321
   at AssetStudio.SerializedProgramParameters..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 510
   at AssetStudio.SerializedSubProgram..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 628
   at AssetStudio.SerializedProgram..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 730
   at AssetStudio.SerializedPass..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 816
   at AssetStudio.SerializedSubShader..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 868
   at AssetStudio.SerializedShader..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 923
   at AssetStudio.Shader..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\Shader.cs:line 1011
   at AssetStudio.AssetsManager.ReadAssets() in D:\a\Studio\Studio\AssetStudio\AssetsManager.cs:line 663
[Error] Unable to load object
Assets unity_builtin_extra

**Comment by Modder4869** [comment]
try disabling shader and you can skip data.unity3d most of the time if error is only that , and it helps no one if you dont at least post sample and game name

**Comment by saveend** [comment]
The problem is the same



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月28日(周六) 凌晨0:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RazTools/Studio] 请问一下，这个问题什么时候能解决 (Issue #32)




 
try disabling shader and you can skip data.unity3d most of the time if error is only that , and it helps no one if you dont at least post sample and game name

**Comment by unk35h** [comment]
如Modder所说，你需要提供游戏名和对应的样例文件，他们才能知道问题在哪，以及如何解决。
As Modder said, you have to provide the game name and sample files. They can know what the issue is and how to solve.

**Comment by saveend** [comment]
> try disabling shader and you can skip data.unity3d most of the time if error is only that , and it helps no one if you dont at least post sample and game name

game link
https://saveend.lanzouj.com/iqOA71d1yiha

**Comment by saveend** [comment]
> try disabling shader and you can skip data.unity3d most of the time if error is only that , and it helps no one if you dont at least post sample and game name

game link
https://saveend.lanzouj.com/iqOA71d1yiha

**Comment by saveend** [comment]
> try disabling shader and you can skip data.unity3d most of the time if error is only that , and it helps no one if you dont at least post sample and game name

圣翼传说
this game Asset Classes is null,Would you mind helping me out with this problem?
