### ISSUE TITLE
Error: Specified argument was out of the range of valid values

### ISSUE THREAD

**Issue by John78964** [RazTools/Studio#36]
Trying to open almost any assetbundle file from game "Overlord: King of Nazarick" (CN game) throws this error:

[Error]
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at AssetStudio.LZ4.Decompress(ReadOnlySpan`1 cmp, Span`1 dec) in D:\a\Studio\Studio\AssetStudio\LZ4\LZ4Utils.cs:line 57
   at AssetStudio.BundleFile.ReadBlocks(FileReader reader, Stream blocksStream) in D:\a\Studio\Studio\AssetStudio\BundleFile.cs:line 556
   at AssetStudio.BundleFile..ctor(FileReader reader, Game game) in D:\a\Studio\Studio\AssetStudio\BundleFile.cs:line 147
   at AssetStudio.AssetsManager.LoadBundleFile(FileReader reader, String originalPath, Int64 originalOffset, Boolean log) in D:\a\Studio\Studio\AssetStudio\AssetsManager.cs:line 257

Here is an example file:
[ainz_m01.zip](https://github.com/RazTools/Studio/files/13422828/ainz_m01.zip) (this file is extracted from apk file)

Is it even possible to open these files?

**Comment by Modder4869** [comment]
use https://assetstudio.lukefz.xyz/download

**Comment by John78964** [comment]
Thank you very much, this works
