### ISSUE TITLE
ExportSplitObjects error

### ISSUE THREAD

**Issue by kovaci1** [RazTools/Studio#37]
Its only me with this error or I miss something to install?

Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.Windows.Forms.TreeNode' to type 'AssetStudioGUI.GameObjectTreeNode'.
   at AssetStudioGUI.Studio.<>c__DisplayClass21_0.<ExportSplitObjects>b__0(Object state) in D:\a\Studio\Studio\AssetStudioGUI\Studio.cs:line 721
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by YueWangChen** [comment]
try del this folder "C:\Users\username\AppData\Local\AssetStudio.GUI"

**Comment by kovaci1** [comment]
Thank you for answering me. This doesn't work on 1.00 ver. I tried and 0.90.4 sane error. Disable shader and animation too. But 0.90.1 work for me without error or last for BH3. I don't know about other game.
