### ISSUE TITLE
GI 4.2 problem

### ISSUE THREAD

**Issue by HyBoxwood** [RazTools/Studio#45]
[- [GUI] fixes #41](https://github.com/RazTools/Studio/actions/runs/7083749739)
```
[Info] Target Game type is GI
[Warning] CABMap is not build, skip resolving dependencies...
[Info] Loading G:\GI\00\02113327.blk_unpacked\00220244_unpacked\CAB-b279e28a16af051274293350e24b3f8c
[Info] Read assets...
[Error] Unable to load object
Assets CAB-b279e28a16af051274293350e24b3f8c
Path
Type AnimationClip
PathID -3925070649274897598
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.Stream.ReadAtLeastCore(Span`1 buffer, Int32 minimumBytes, Boolean throwOnEndOfStream)
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt64()
   at AssetStudio.EndianBinaryReader.ReadInt64() in D:\a\Studio\Studio\AssetStudio\EndianBinaryReader.cs:line 58
   at AssetStudio.PPtr`1..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\PPtr.cs:line 27
   at AssetStudio.AnimationClipBindingConstant..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\AnimationClip.cs:line 1642
   at AssetStudio.AnimationClip..ctor(ObjectReader reader) in D:\a\Studio\Studio\AssetStudio\Classes\AnimationClip.cs:line 1884
   at AssetStudio.AssetsManager.ReadAssets() in D:\a\Studio\Studio\AssetStudio\AssetsManager.cs:line 650
[Info] Process Assets...
```

**Comment by Modder4869** [comment]
why unpacked?

**Comment by HyBoxwood** [comment]
In order to collect quest image assets for the wiki, something not had been uploaded.

**Comment by Modder4869** [comment]
then you can ignore animation clips error it wont affect what you looking for

**Comment by HyBoxwood** [comment]
In order to gather image assets used in tasks and upload them to the wiki, those files that have never been uploaded

**Comment by HyBoxwood** [comment]
这样的话我就无法加载所有文件然后按照文件结构导出了，之前我在Honkai: Star Rail是可以设置Group exported assets为container path的，但是Genshin Impact没有成功过，会这样报错然后一直持续到内存溢出。我现在有16GB*2的物理内存还是无法加载完Genshin Impact的文件。
In this case, I'm unable to load all the files and then export them according to the file structure. Previously in Honkai: Star Rail, I could set 'Group exported assets' as the container path, but it hasn't been successful in Genshin Impact. It throws an error like this and continues until it causes a memory overflow. Even with 16GB*2 of physical memory, I'm still unable to load all of Genshin Impact's files.

**Comment by Modder4869** [comment]
read the guide linked in readme , and genshin doesnt have container names

**Comment by Razmoth** [comment]
Greetings,

Should be fixed now.
