### ISSUE TITLE
PGR Global UnityCN key changed

### ISSUE THREAD

**Issue by jerycho007** [RazTools/Studio#57]
Hi,
did the key for Punishing Gray Raven Global change?
Cannot open any of the files.

> [Verbose] [AssetsManager] Cleaning up...
[Verbose] [ImportHelper] Processing split assets (.splitX) prior to loading files...
[Verbose] [ImportHelper] Found 0 split files, attempting to merge...
[Verbose] [ImportHelper] Filter out paths that has .split and has the same name
[Warning] CABMap is not build, skip resolving dependencies...
[Verbose] [AssetsManager] caching E:\New\Games\PGR\PGR_Data\StreamingAssets\resource\matrix\00ae6ff2e893fffae3c9c532a087c932983c95e0 path and name to filter out duplicates
[Verbose] [FileReader] Parsed signature is UnityFS
[Verbose] [FileReader] File E:\New\Games\PGR\PGR_Data\StreamingAssets\resource\matrix\00ae6ff2e893fffae3c9c532a087c932983c95e0 type is BundleFile
[Verbose] [FileReaderExtensions] Applying preprocessing to file 00ae6ff2e893fffae3c9c532a087c932983c95e0
[Verbose] [FileReaderExtensions] File is encrypted !!
[Verbose] [FileReaderExtensions] No preprocessing is needed
[Info] Loading E:\New\Games\PGR\PGR_Data\StreamingAssets\resource\matrix\00ae6ff2e893fffae3c9c532a087c932983c95e0
[Verbose] [BundleFile] Parsed signature UnityFS
[Verbose] [BundleFile] Bundle header Info: signature: UnityFS | version: 6 | unityVersion: 5.x.x | unityRevision: 2018.4.30f1 | size: 0x000FA7F4 | compressedBlocksInfoSize: 0x0000007F | uncompressedBlocksInfoSize: 0x000000DF | flags: 0x00000243
[Verbose] [BundleFile] Attempting to decrypt file 00ae6ff2e893fffae3c9c532a087c932983c95e0 with UnityCN encryption
[Verbose] [BundleFile] Mask set to BlockInfoNeedPaddingAtStart
[Verbose] [BundleFile] Encryption flag exist, file is encrypted, attempting to decrypt
[Verbose] [UnityCN] Decrypted signature is ??dek1??B?jo?@3
[Error] Error while reading bundle file E:\New\Games\PGR\PGR_Data\StreamingAssets\resource\matrix\00ae6ff2e893fffae3c9c532a087c932983c95e0
System.Exception: Invalid Signature, Expected #$unity3dchina!@ but found ??dek1??B?jo?@3 instead
   at AssetStudio.UnityCN..ctor(EndianBinaryReader reader) in D:\a\Studio\Studio\AssetStudio\Crypto\UnityCN.cs:line 34
   at AssetStudio.BundleFile.ReadUnityCN(FileReader reader) in D:\a\Studio\Studio\AssetStudio\BundleFile.cs:line 401
   at AssetStudio.BundleFile..ctor(FileReader reader, Game game) in D:\a\Studio\Studio\AssetStudio\BundleFile.cs:line 142
   at AssetStudio.AssetsManager.LoadBundleFile(FileReader reader, String originalPath, Int64 originalOffset, Boolean log) in D:\a\Studio\Studio\AssetStudio\AssetsManager.cs:line 260
[Verbose] [AssetsHelper] Cleared cached offsets
[Info] Read assets...
[Info] Process Assets...

**Comment by jerycho007** [comment]
ah so the CN key works my bad closing this
