### ISSUE TITLE
Zstd decompression error. Encrypted?

### ISSUE THREAD

**Issue by rojok23** [RazTools/Studio#62]
Hello, when I try to open certain files I get the following error;

`Zstd decompression error:
ZstdSharp.ZstdException: Unknown frame descriptor
   at ZstdSharp.ThrowHelper.ThrowException(UIntPtr returnValue, String message)
   at ZstdSharp.ThrowHelper.EnsureZstdSuccess(UIntPtr returnValue)
   at ZstdSharp.Decompressor.Unwrap(ReadOnlySpan`1 src, Span`1 dest)
   at ZstdSharp.Decompressor.Unwrap(Byte[] src, Int32 srcOffset, Int32 srcLength, Byte[] dst, Int32 dstOffset, Int32 dstLength)
   at AssetStudio.BundleFile.ReadBlocks(FileReader reader, Stream blocksStream) in D:\a\Studio\Studio\AssetStudio\BundleFile.cs:line 646`

Is this related to encryption or some other issue?

**Comment by Modder4869** [comment]
cant tell , send sample , game name , studio commit hash (in titlebar)

**Comment by Razmoth** [comment]
Greetings,

This is because some of the compressed `Zstd` block trains a custom dictionary to be used for compressing/decompressing, so without that it won't be possible to decompress said block.
