### ISSUE TITLE
How to open .dab files?

### ISSUE THREAD

**Issue by YinCQL** [RazTools/Studio#87]
<img width="516" alt="image" src="https://github.com/RazTools/Studio/assets/71113782/0dfd5a49-ea50-4c1a-b05c-1fcc350ee1f7">

[Info] Loading E:\GuiLongchao\game\GuiLongchao_Data\StreamingAssets\Assetbundle\fc3afd644343d34a6b977efff218a459.dab
[Error] Error while reading bundle file E:\GuiLongchao\game\GuiLongchao_Data\StreamingAssets\Assetbundle\fc3afd644343d34a6b977efff218a459.dab
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at AssetStudio.LZ4.Decompress(ReadOnlySpan`1 cmp, Span`1 dec) in D:\a\Studio\Studio\AssetStudio\LZ4\LZ4Utils.cs:line 57
   at AssetStudio.BundleFile.ReadBlocks(FileReader reader, Stream blocksStream) in D:\a\Studio\Studio\AssetStudio\BundleFile.cs:line 587
   at AssetStudio.BundleFile..ctor(FileReader reader, Game game) in D:\a\Studio\Studio\AssetStudio\BundleFile.cs:line 148
   at AssetStudio.AssetsManager.LoadBundleFile(FileReader reader, String originalPath, Int64 originalOffset, Boolean log) in D:\a\Studio\Studio\AssetStudio\AssetsManager.cs:line 243

**Comment by Modder4869** [comment]
follow the issue template when making one
